name:                Haskforce
version:             0.1.0.0
github:              "githubuser/Haskforce"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/Haskforce#readme>

dependencies:
- base >= 4.7 && < 5
- http-types
- http-conduit
- http-client
- wreq
- bytestring
- aeson
- yaml
- lens
- text
- hspec
- transformers
- hashmap
- containers
- servant
- servant-client
- http-api-data
- http-client-tls
library:
  source-dirs: src

executables:
  Haskforce-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskforce
    - http-types
    - http-conduit
    - wreq
    - bytestring
    - aeson
    - yaml
    - lens
    - text
    - mtl
    - http-client
    - transformers
    - hashmap
    - containers
tests:
  Haskforce-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskforce
    - hspec
    - http-client
    - transformers
    - hashmap
    - containers